name: Push Demo

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Print Welcome Message
        run: echo "Welcome to GitHub Actions"

      - name: Print Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Print Trigger Event
        run: echo "Triggered by ${{ github.event_name }}"

      - name: Print Date
        run: date
